apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: httpd
  namespace: production
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: httpd
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: production
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 70
